slam_toolbox:
  ros__parameters:
    # General
    use_sim_time: false
    mode: mapping               # Mapping mode
    map_file_name: ""           # Leave empty for live mapping
    map_publish_period: 1.0     # Publish map every 1 second
    map_update_interval: 0.5    # Map update interval in seconds

    # Frames
    scan_topic: /scan
    base_frame: base_link
    odom_frame: odom
    map_frame: map

    # Laser processing
    max_laser_range: 10.0       # Maximum lidar range in meters
    min_laser_range: 0.1        # Minimum lidar range in meters
    laser_queue_size: 50        # Avoid dropped messages

    # Optimization
    optimize_every_n_nodes: 5
    max_nodes_to_retain: 5000

    # Misc
    publish_tf: true             # Broadcast map->odom transform
    use_scan_matching: true      # Enable scan matching for better mapping
