amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"          # replace with your laser topic if different
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
