amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_link
    odom_frame_id: odom
    scan_topic: scan

map_server:
  ros__parameters:
    yaml_filename: ~/maps/my_map.yaml

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0

controller_server:
  ros__parameters:
    expected_controller_frequency: 10.0
